{
 "title": "UPB Remote Solar Lab",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "CS320 Integral Solar Radiation Sensor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE(datetime, '%Y-%m-%d %H:%i') AS time, solarRadiationCS320 as Cochabamba from Datalogger\r\n"
    },
    {
     "rawSql": "SELECT STR_TO_DATE(datetime, '%Y-%m-%d %H:%i') AS time, solarRadiationCS320Avg as SantaCruz from DataloggerSCZ"
    },
    {
     "rawSql": "SELECT STR_TO_DATE(datetime, '%Y-%m-%d %H:%i') AS time, solarRadiationCS320Avg as LaPaz  from DataloggerLPZ\r\n"
    }
   ]
  },
  {
   "title": "UVA Radiation Sensor SU202",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE(datetime, '%Y-%m-%d %H:%i') AS time, uvaRadiationSU202Avg as Cochabamba from Datalogger"
    },
    {
     "rawSql": "SELECT STR_TO_DATE(datetime, '%Y-%m-%d %H:%i') AS time, uvaRadiationSU202Avg as SantaCruz from DataloggerSCZ"
    },
    {
     "rawSql": "SELECT STR_TO_DATE(datetime, '%Y-%m-%d %H:%i') AS time, uvaRadiationSU202Avg as LaPaz from DataloggerLPZ"
    }
   ]
  },
  {
   "title": "CMP 6 Integral Solar Radiation Sensor",
   "type": "timeseries",
   "description": "This sensor is only available in Cochabamba",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE(datetime, '%Y-%m-%d %H:%i') AS time, solarRadiationCMPAvg as Cochabamba from Datalogger\r\n"
    }
   ]
  },
  {
   "title": "LP UVA 02 Radiation Sensor",
   "type": "timeseries",
   "description": "This sensor is only available in Cochabamba",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT STR_TO_DATE(datetime, '%Y-%m-%d %H:%i') AS time, uvaRadiationLPAvg as Cochabamba from Datalogger\r\n"
    }
   ]
  }
 ]
}